# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Saunby.net
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I'm Michael Saunby. Public speaking and outreach things, such as hackathons, get a brief note here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.saunby.net" # the base hostname & protocol for your site
linkedin_username: minchaelsaunby
github_username:  msaunby
collections:
  recent:
    output: true
  archive:
    output: true
  museum:
    output: true


# Build settings
markdown: kramdown

