# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Saunby.net
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I'm Michael Saunby; a member of the recently formed
  <a href='http://www.informaticslab.co.uk'>Met Office Informatics Lab.</a>
  Speaking and outreach things, such as hackathons get a brief note here. Stuff I'm making is more likely to be covered in my
  blog <a href='http://mike.saunby.net'>mike.saunby.net</a>
baseurl: "/saunby-net" # the subpath of your site, e.g. /blog
url: "http://msaunby.github.io/" # the base hostname & protocol for your site
twitter_username: msaunby
github_username:  msaunby

# Build settings
markdown: kramdown
